name       : dosbox
version    : 0.74
release    : 2
source     :
    - http://heanet.dl.sourceforge.net/project/dosbox/dosbox/0.74/dosbox-0.74.tar.gz : 13f74916e2d4002bad1978e55727f302ff6df3d9be2f9b0e271501bd0a938e05
license    : GPL-2.0
component  : games.emulator
summary    : An Open Source DOS emulator to run old DOS games
description: |
    DOSBox emulates a full x86 pc with sound and DOS
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gl)
    - pkgconfig(glu)
    - pkgconfig(libpng)
    - pkgconfig(SDL_net)
    - sdl1-sound-devel
setup      : |
    %patch -p1 < $pkgfiles/dosbox-0.74_gcc4.6_compat.patch
    %configure
build      : |
    %make
install    : |
    %make_install
    install -Dm644 README $installdir/usr/share/doc/dosbox/README
    install -Dm644 docs/README.video $installdir/usr/share/doc/dosbox/README.video
    install -Dm644 $pkgfiles/dosbox.png $installdir/usr/share/pixmaps/dosbox.png
    install -Dm644 $pkgfiles/dosbox.desktop $installdir/usr/share/applications/dosbox.desktop
