name       : dosbox
version    : 0.74.2
release    : 5
source     :
    - https://netix.dl.sourceforge.net/project/dosbox/dosbox/0.74-2/dosbox-0.74-2.tar.gz : 7077303595bedd7cd0bb94227fa9a6b5609e7c90a3e6523af11bc4afcb0a57cf
license    : GPL2.0-or-later
component  : games.emulator
summary    : An Open Source DOS emulator to run old DOS games
description: |
    DOSBox emulates a full x86 pc with sound and DOS
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gl)
    - pkgconfig(glu)
    - pkgconfig(libpng)
    - pkgconfig(SDL_net)
    - sdl1-sound-devel
setup      : |
    %patch -p1 < $pkgfiles/dosbox-0.74_gcc4.6_compat.patch
    %configure
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 README $installdir/usr/share/doc/dosbox/README
    install -Dm00644 docs/README.video $installdir/usr/share/doc/dosbox/README.video
    install -Dm00644 $pkgfiles/dosbox.png $installdir/usr/share/pixmaps/dosbox.png
    install -Dm00644 $pkgfiles/dosbox.desktop $installdir/usr/share/applications/dosbox.desktop
